import foodBusinessImage1 from './food-business-image-1.jpg';

function filterYelpData(location, term, radius, sortBy) {
  if (location && term && radius && sortBy) {
    return [
      {
        imageSrc: foodBusinessImage1,
        imageAlt: 'Add description',
        name: "Kanyi's Corner",
        address: '122 Sunnyhill Street',
        city: 'Fairy Town',
        state: 'Fairytale Land',
        zipCode: 8888,
        category: 'lacto-ovo vegetarian',
        rating: 4.8,
        reviewCount: 120,
      },
      {
        imageSrc: foodBusinessImage1,
        name: "Kanyi's Corner",
        address: '122 Sunnyhill Street',
        city: 'Fairy Town',
        state: 'Fairytale Land',
        zipCode: 8888,
        category: 'lacto-ovo vegetarian',
        rating: 4.8,
        reviewCount: 120,
      },
      {
        imageSrc: foodBusinessImage1,
        name: "Kanyi's Corner",
        address: '122 Sunnyhill Street',
        city: 'Fairy Town',
        state: 'Fairytale Land',
        zipCode: 8888,
        category: 'lacto-ovo vegetarian',
        rating: 4.8,
        reviewCount: 120,
      },
      {
        imageSrc: foodBusinessImage1,
        name: "Kanyi's Corner",
        address: '122 Sunnyhill Street',
        city: 'Fairy Town',
        state: 'Fairytale Land',
        zipCode: 8888,
        category: 'lacto-ovo vegetarian',
        rating: 4.8,
        reviewCount: 120,
      },
      {
        imageSrc: foodBusinessImage1,
        name: "Kanyi's Corner",
        address: '122 Sunnyhill Street',
        city: 'Fairy Town',
        state: 'Fairytale Land',
        zipCode: 8888,
        category: 'lacto-ovo vegetarian',
        rating: 4.8,
        reviewCount: 120,
      },
      {
        imageSrc: foodBusinessImage1,
        name: "Kanyi's Corner",
        address: '122 Sunnyhill Street',
        city: 'Fairy Town',
        state: 'Fairytale Land',
        zipCode: 8888,
        category: 'lacto-ovo vegetarian',
        rating: 4.8,
        reviewCount: 120,
      },
      {
        imageSrc: foodBusinessImage1,
        name: "Kanyi's Corner",
        address: '122 Sunnyhill Street',
        city: 'Fairy Town',
        state: 'Fairytale Land',
        zipCode: 8888,
        category: 'lacto-ovo vegetarian',
        rating: 4.8,
        reviewCount: 120,
      },
      {
        imageSrc: foodBusinessImage1,
        name: "Kanyi's Corner",
        address: '122 Sunnyhill Street',
        city: 'Fairy Town',
        state: 'Fairytale Land',
        zipCode: 8888,
        category: 'lacto-ovo vegetarian',
        rating: 4.8,
        reviewCount: 120,
      },
      {
        imageSrc: foodBusinessImage1,
        name: "Kanyi's Corner",
        address: '122 Sunnyhill Street',
        city: 'Fairy Town',
        state: 'Fairytale Land',
        zipCode: 8888,
        category: 'lacto-ovo vegetarian',
        rating: 4.8,
        reviewCount: 120,
      },
    ];
  }
}

export default filterYelpData;
